import 'package:flutter/material.dart';

import '../animal_icons_icons.dart';

Map<String, IconData> animalIconMap = {
  "horse_silhouette": AnimalIcons.horse_silhouette,
  "running_dog_silhouette": AnimalIcons.running_dog_silhouette,
  "wallaby_mammal_animal_silhouette":
      AnimalIcons.wallaby_mammal_animal_silhouette,
  "tapir_mammal_shape_from_side": AnimalIcons.tapir_mammal_shape_from_side,
  "cheetah_feline_silhouette": AnimalIcons.cheetah_feline_silhouette,
  "domestic_cat_shape": AnimalIcons.domestic_cat_shape,
  "mammal_seal_shape": AnimalIcons.mammal_seal_shape,
  "sea_lion_mammal_animal_shape": AnimalIcons.sea_lion_mammal_animal_shape,
  "rhino_side_view_silhouette": AnimalIcons.rhino_side_view_silhouette,
  "hippo_shape": AnimalIcons.hippo_shape,
  "porcupine_shape": AnimalIcons.porcupine_shape,
  "cow_silhouette": AnimalIcons.cow_silhouette,
  "mammal_ferret_shape": AnimalIcons.mammal_ferret_shape,
  "ostrich_bird_shape_running": AnimalIcons.ostrich_bird_shape_running,
  "pig_side_view_silhouette": AnimalIcons.pig_side_view_silhouette,
  "manatee_mammal_animal_shape": AnimalIcons.manatee_mammal_animal_shape,
  "manatee_shape": AnimalIcons.manatee_shape,
  "running_lion": AnimalIcons.running_lion,
  "lemur_shape": AnimalIcons.lemur_shape,
  "koala_silhouette": AnimalIcons.koala_silhouette,
  "kangaroo_shape": AnimalIcons.kangaroo_shape,
  "tiger": AnimalIcons.tiger,
  "deer_shape": AnimalIcons.deer_shape,
  "hyena_shape": AnimalIcons.hyena_shape,
  "falcon_bird_shape": AnimalIcons.falcon_bird_shape,
  "giraffe_silhouette": AnimalIcons.giraffe_silhouette,
  "crocodile_shape": AnimalIcons.crocodile_shape,
  "turtle_silhouette": AnimalIcons.turtle_silhouette,
  "turtle_shape": AnimalIcons.turtle_shape,
  "flamingo": AnimalIcons.flamingo,
  "deer_silhouette": AnimalIcons.deer_silhouette,
  "elephant_side_view": AnimalIcons.elephant_side_view,
  "sheep": AnimalIcons.sheep,
  "camel_shape": AnimalIcons.camel_shape,
  "monkey": AnimalIcons.monkey,
  "antelope_silhouette_from_side_view":
      AnimalIcons.antelope_silhouette_from_side_view,
  "ant_eater_shape": AnimalIcons.ant_eater_shape,
  "mammal_animal_aardvark_shape": AnimalIcons.mammal_animal_aardvark_shape,
  "bird_osprey_shape": AnimalIcons.bird_osprey_shape,
  "monkey_shape": AnimalIcons.monkey_shape,
  "fox_shape": AnimalIcons.fox_shape,
  "bear_black_shape": AnimalIcons.bear_black_shape,
  "dog_shape": AnimalIcons.dog_shape,
};
